### PR TITLE
Zhilong fixed the error in the model_parameter.py

### PR DESCRIPTION
**Pull request by zfang-slim**
Zhilong modify the function 'add_padding' in the file /pysit/solvers/model_parameter.py

The correct order for the axis of the model is 'x, z' for 2d and 'x, y, z' for 3d. In the previous version, Zhilong mistakenly uses 'z, x' and 'z, x, y', which will result in errors when remapping the model from the computational domain to the physical domain. Now, Zhilong has fixed the mistake.

### CODE REVIEW

**Comment by rhewett** [comment]
@zfang-slim can you resubmit this with only the lines that need to be changed at this time?  There are so many changes I can't find the relevant parts in the PR.

It may be helpful to use `git add -u -p` to let you choose which patches to add to a commit.  

Minimizing the changes to a small number of related changes per commit and per PR makes reviewing much easier.

**Comment by rhewett** [comment]
Also, note you don't have to create a new PR.  You can just correct the branch and push the new smaller commit, if you want.

**Comment by zfang-slim** [comment]
Hello, Russell,

Sorry, I need to check the comparison first. I will highlight the differences. By the way, do you mean that I can directly correct at the master branch?


Zhilong

**Comment by zfang-slim** [comment]
Zhilong is remaking a new PR

**Comment by rhewett** [comment]
@zfang-slim thanks, can you do one more thing?  Squash these two commits.

The easiest way to do this is with an interactive rebase.  https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit

**Pull request closed without merging**
