### PR TITLE
Zhilong resubmit the modification of model_parameter.py

### PR DESCRIPTION
**Pull request by zfang-slim**
Zhilong remake the file model_parameter.py so that the changes are minimal.

### CODE REVIEW

**Comment by rhewett** [comment]
@zfang-slim thanks, can you do one more thing? Squash these two commits.

The easiest way to do this is with an interactive rebase. https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit

Note, you dont have to close and open a new PR, just updating the branch as described in the docs i linked will update the PR.

**Comment by rhewett** [comment]
To explain why, a cleaner git history helps with debugging and tracking even the history of individual lines.  So when a PR is submitted, I personally believe that it is better to get concise commits with a single set of changes.  To do this, it is often necessary to rebase and remove changes that have no impact on the final PR.  If you need help with it let me know.  This is all about getting better with git.

**Comment by zfang-slim** [comment]
Thanks, Russell, I totally agree with your suggestion. I will follow your suggestions.

**Comment by zfang-slim** [comment]
Hello, Russell, I have squashed the two commits and update my branch. Could you have a look at it? Thanks.

**Comment by rhewett** [comment]
looks good!

**Pull request merged**
